const db = require("../config/database");
const PDFDocument = require("pdfkit");
const moment = require("moment");

exports.downloadPDF = (req, res) => {
  const device_id = "1"; // ID Alat

  const sql =
    "SELECT * FROM daily_logs WHERE device_id = ? ORDER BY log_date DESC";

  db.query(sql, [device_id], (err, results) => {
    if (err) {
      console.error(err);
      return res.status(500).send("Database Error");
    }

    // --- PERBAIKAN DI SINI (ParseFloat) ---
    const totalHari = results.length;

    // Gunakan parseFloat agar tidak dianggap string
    const totalBiaya = results.reduce(
      (acc, row) => acc + parseFloat(row.estimated_cost || 0),
      0
    );
    const totalPump = results.reduce(
      (acc, row) => acc + (row.total_usage || 0),
      0
    );

    // Setup PDF
    const doc = new PDFDocument({ margin: 50 });
    const filename = `Laporan_${moment().format("YYYY-MM-DD")}.pdf`;

    res.setHeader("Content-disposition", `attachment; filename="${filename}"`);
    res.setHeader("Content-type", "application/pdf");

    doc.pipe(res);

    // === JUDUL ===
    doc
      .fontSize(20)
      .font("Helvetica-Bold")
      .text("LAPORAN SMART SANITIZER", { align: "center" });
    doc
      .fontSize(10)
      .font("Helvetica")
      .text("Generated by IoT System", { align: "center" });
    doc.moveDown(2);

    // === KOTAK RINGKASAN ===
    doc.rect(50, 130, 500, 90).stroke(); // Kotak Border

    doc.fontSize(12).font("Helvetica-Bold").text("Ringkasan Total:", 70, 145);
    doc.moveDown(0.5);

    doc.font("Helvetica").fontSize(11);
    doc.text(`Total Hari Aktif       : ${totalHari} Hari`, 70);
    doc.text(`Total Pemakaian    : ${totalPump} Kali`, 70);

    // Format Rupiah yang rapi (tanpa desimal .00 yang panjang)
    doc.text(
      `Total Biaya             : Rp ${totalBiaya.toLocaleString("id-ID")}`,
      70
    );

    doc.text(`Tanggal Cetak        : ${moment().format("DD MMMM YYYY")}`, 70);

    doc.moveDown(4);

    // === TABEL RINCIAN ===
    const tableTop = 250;
    doc
      .font("Helvetica-Bold")
      .fontSize(12)
      .text("Rincian Harian:", 50, tableTop - 25);

    // Header Tabel
    const colDate = 50;
    const colUsage = 250;
    const colCost = 400;

    doc.fontSize(10);
    doc.text("TANGGAL", colDate, tableTop, { bold: true });
    doc.text("JUMLAH PUMP", colUsage, tableTop, { bold: true });
    doc.text("BIAYA", colCost, tableTop, { bold: true });

    // Garis Bawah Header
    doc
      .moveTo(50, tableTop + 15)
      .lineTo(550, tableTop + 15)
      .stroke();

    // Isi Tabel
    let rowY = tableTop + 30;
    doc.font("Helvetica");

    results.forEach((row) => {
      // Halaman baru jika penuh
      if (rowY > 700) {
        doc.addPage();
        rowY = 50;
      }

      const dateStr = moment(row.log_date).format("DD MMM YYYY");
      const usageStr = `${row.total_usage} Kali`;
      const costStr = `Rp ${parseFloat(row.estimated_cost).toLocaleString(
        "id-ID"
      )}`;

      doc.text(dateStr, colDate, rowY);
      doc.text(usageStr, colUsage, rowY);
      doc.text(costStr, colCost, rowY);

      rowY += 20;
    });

    doc.end();
  });
};
